# Set the necessary paths
directories:
  DATA_DIR: '/media/data/bruppik/cvg11/Pix4D/example_cadastre'
  MODEL_WEIGHTS_DIR: '/media/data/bruppik/pytorch-deeplab-resnet/pth/'
  IMAGE_DIR: '/media/data/bruppik/pytorch-deeplab-resnet/images/'

  annotations:

  inference:

  lists:
    DATA_INFERENCE_LIST_PATH: '/media/data/bruppik/pytorch-deeplab-resnet/lists/inference.txt'

  training:

# Properties of the image and labels
INPUT_SIZE: '1500,2000'
# In the MATLAB semanticLabelingTool the class
# 'undefined' is labeled with index '0'
IGNORE_LABEL: 0

# NUM_CLASSES is the actual number of classes, so if your classes
# are indexed by 0, 1, ..., 27 you should set NUM_CLASSES = 28
NUM_CLASSES: 28
NUM_VALIDATION_IMAGES: 1


# File that is used for restoring weights of the network
RESTORE_FROM: '/media/data/bruppik/pytorch-deeplab-resnet/pth/VOC12_scenes_16000.pth'